name: gnn
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h6c40b1e_6
  - ca-certificates=2025.7.15=hecd8cb5_0
  - expat=2.7.1=h6d0c2b6_0
  - libcxx=19.1.7=haebbb44_3
  - libffi=3.4.4=hecd8cb5_1
  - ncurses=6.5=h923df54_0
  - openssl=3.0.17=hee2dfae_0
  - pip=25.3=pyhc872135_0
  - python=3.10.18=hc958d9f_0
  - readline=8.3=h49f2429_0
  - setuptools=78.1.1=py310hecd8cb5_0
  - sqlite=3.50.2=hc8b0dd6_1
  - tk=8.6.15=h3a5a201_0
  - wheel=0.45.1=py310hecd8cb5_0
  - xz=5.6.4=h46256e1_1
  - zlib=1.2.13=h4b97444_1
  - pip:
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.2
    - aiosignal==1.4.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - certifi==2025.11.12
    - charset-normalizer==3.4.4
    - contourpy==1.3.2
    - cycler==0.12.1
    - filelock==3.20.0
    - fonttools==4.60.1
    - frozenlist==1.8.0
    - fsspec==2025.10.0
    - idna==3.11
    - jinja2==3.1.6
    - joblib==1.5.2
    - kiwisolver==1.4.9
    - markupsafe==3.0.3
    - matplotlib==3.10.7
    - mpmath==1.3.0
    - multidict==6.7.0
    - networkx==3.4.2
    - numpy==1.26.4
    - packaging==25.0
    - pandas==2.3.3
    - pillow==12.0.0
    - propcache==0.4.1
    - psutil==7.1.3
    - pyparsing==3.2.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.5
    - scikit-learn==1.7.2
    - scipy==1.15.3
    - six==1.17.0
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - torch==2.2.2
    - torch-geometric==2.7.0
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - xxhash==3.6.0
    - yarl==1.22.0
prefix: /Users/gaspardlafont/opt/anaconda3/envs/gnn
